import express, { Request, Response } from 'express';
import { AppConfig } from './types';

export function createRuntimeServer(config: AppConfig) {
  const app = express();
  app.use(express.json());

  app.get('/api/config', (_, res: Response) => {
    res.json({ success: true, config });
  });

  for (const route of config.design.apiRoutes) {
    const handler = (req: Request, res: Response) => {
      const payload = {
        route: route.id,
        method: route.method,
        path: route.path,
        sampleResponse: Object.fromEntries(
          Object.entries(route.responseSchema).map(([key, field]) => [key, sampleValue(field.type)])
        ),
      };
      res.json(payload);
    };

    switch (route.method) {
      case 'GET':
        app.get(route.path, handler);
        break;
      case 'POST':
        app.post(route.path, handler);
        break;
      case 'PUT':
        app.put(route.path, handler);
        break;
      case 'PATCH':
        app.patch(route.path, handler);
        break;
      case 'DELETE':
        app.delete(route.path, handler);
        break;
    }
  }

  app.use((req, res) => {
    res.status(404).json({ error: 'Route not generated by runtime', path: req.path });
  });

  return app;
}

function sampleValue(type: string) {
  switch (type) {
    case 'number':
      return 0;
    case 'boolean':
      return false;
    case 'date':
      return new Date().toISOString();
    case 'json':
      return {};
    default:
      return '';
  }
}

export function inspectConfig(config: AppConfig) {
  const routes = config.design.apiRoutes.map((route) => `${route.method} ${route.path}`);
  const pageRoutes = config.design.pages.map((page) => page.path);
  return {
    routeCount: routes.length,
    pageCount: pageRoutes.length,
    entities: config.design.entities.map((entity) => entity.name),
    routes,
    pageRoutes,
  };
}

export function validateRuntime(config: AppConfig) {
  const issues: string[] = [];
  const seen = new Set<string>();

  for (const route of config.design.apiRoutes) {
    if (!route.path.startsWith('/api/')) {
      issues.push(`Runtime route path must start with /api/: ${route.path}`);
    }
    if (!['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].includes(route.method)) {
      issues.push(`Unsupported HTTP method: ${route.method} on ${route.path}`);
    }
    const key = `${route.method} ${route.path}`;
    if (seen.has(key)) {
      issues.push(`Duplicate runtime endpoint: ${key}`);
    }
    seen.add(key);
    if (Object.entries(route.responseSchema).length === 0) {
      issues.push(`Runtime route ${route.id} has an empty response schema.`);
    }
  }

  return issues;
}
